### PR TITLE
Adding collapse button for attachments

### PR DESCRIPTION
**Pull request by ghost**
https://user-images.githubusercontent.com/35100156/106916090-1635f900-6707-11eb-9a6f-d07968ba76fb.mov

### CODE REVIEW

**Review by schmijos — APPROVED** [review]
Noice! But no idea how deployment would work. @macav ?

**Comment by coorasse** [comment]
Is it open by default or closed? Because we work a lot with the attachments also with the clients and I'd like them to be open by default if possible

**Comment by ghost** [comment]
@coorasse and @schmijos could you maybe come to an agreement on collapsed vs open by default :) seems like ale wants em open by default and josua collapsed ^^ I don't mind either way 👍🏻

**Comment by ghost** [comment]
At the moment default is collapsed as per schmijos request.

**Comment by macav** [comment]
It needs to be pulled as a submodule in the Redmine project and that change in the submodule REF needs to be pushed. That's going to be deployed automatically.

**Comment by schmijos** [comment]
Since not everyone wants to have it collapsed per default, let's rediscuss my issue. Currently I have problems with duplicate attachments. We often communicate via comments which have attached files. These files are shown in the comment and in the attachments list. This led to confusion in the past, because: which attachment is the relevant one?

**What about just moving the attachments list to the bottom instead (below the conversations)?**

See screenshot as example for the problem.

https://renuo.slack.com/files/U0E2W52C8/F01MADNK46Q/redmine.renuo.ch_issues_15116.png

**Comment by ghost** [comment]
I mean ^^ If you want I can also add a setting in the redmine repo so that you can configure it per user ?

**Comment by schmijos** [comment]
Let's await @coorasse answer first. Moving the attachments section to the bottom would be the easiest solution.

**Comment by schmijos** [comment]
@coorasse doesn't approve.
Let's change the default state to uncollapsed please. I'm fine with that actually.

**Comment by schmijos** [comment]
@coorasse has even more doubts. Sorry @Liberatys, let's close this. My feature request seem to be too controversial.

**Pull request closed without merging**
